<a href="https://colab.research.google.com/github/DevKaiqueTeixeira/IA/blob/main/ExercicioLista2_Python_KaiqueDeLimaTeixeira_6periodo_TurmaC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
print("Lista 2")

print("Estudos fora da lista")

import numpy as np

array = np.array([1,2,3,4,5,6])
print(array)

array_zeros = np.zeros((3,3))

array_rand = np.random.rand(4)

print(array_zeros)
print(array_rand)

#Soma com NUMPY
array1 = np.array([5,5,5,5,5])

array2 = np.array([1,2,3,4,5,])

soma = np.add(array1,array2)

produto=np.dot(array1,array2)

print(f"Soma: {soma}")

media = np.mean(array1)
print(f"Média: {media}")
print(f"Produto: {produto}")
desvio = np.std(array1)

print(f"Desvio padrão: {desvio}")

#Fatiamento de array


arrayfatia = np.array([[1,2,3] , [4,5,6,], [7,8,9]])
primeira_linha = arrayfatia[0, :]
array_reshaped = np.reshape(arrayfatia, (1, 9 ))
print(arrayfatia)
print(array_reshaped)

a = np.array([[1,2] , [4,5]])

inversionMatriz = np.linalg.det(a)
print(f"Inversão matriz: {inversionMatriz}")

aleatorios= np.random.randint(10)
print(f"Aleatório {aleatorios}")

Lista 2
Estudos fora da lista
[1 2 3 4 5 6]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0.80346064 0.21255769 0.37555846 0.50297442]
Soma: [ 6  7  8  9 10]
Média: 5.0
Produto: 75
Desvio padrão: 0.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
Inversão matriz: -2.9999999999999996
Aleatório 3


In [60]:
print("Exercício  Manipulação array")
import numpy as np

#array 3x3
array = np.random.randint(0, 10, (3, 3))
print(f"Array padrão: ")
print(array)

max_value =  np.max(array)
print(f"Maior número: {max_value}")

min_value =  np.min(array)
print(f"Maior número: {min_value}")

sum_value = np.sum(array)
print(f"Soma dos elementos: {sum_value}")



Exercício  Manipulação array
Array padrão: 
[[5 0 5]
 [2 4 3]
 [3 9 7]]
Maior número: 9
Maior número: 0
Soma dos elementos: 38


In [61]:
print("Exercício  Produto escalar entre vetores")

import numpy as np

vetor1 = np.array([1,2,3])
vetor2 = np.array([4,5,6])

produto_escalar = np.dot(vetor1, vetor2)
print(f"Produto escalar: {produto_escalar}")

Exercício  Produto escalar entre vetores
Produto escalar: 32


In [62]:
print("Exercício  Operações matemática ")

import numpy as np

array = np.array([[1,2], [3,4]])

array2 = np.array([[1,2], [3,4]])

soma = array + array2

print(f"Soma dos arrays: {soma}")

multiplicar = array * array2
print(f"Multiplicar dos arrays: {multiplicar}")

subtrair = array - array2
print(f"Subtrair dos arrays: {subtrair}")





Exercício  Operações matemática 
Soma dos arrays: [[2 4]
 [6 8]]
Multiplicar dos arrays: [[ 1  4]
 [ 9 16]]
Subtrair dos arrays: [[0 0]
 [0 0]]


In [63]:
print("Exercício 4 Otimização de Funções")

from scipy.optimize import minimize

def f(x):
  return 10+10+10


resultado = minimize(f,0)

print(f"Minimo encontrado{resultado.fun}")
print(f"Valor de X {resultado.x}")

Exercício 4 Otimização de Funções
Minimo encontrado30
Valor de X [0.]


In [64]:
print("Exercicio 1 Numpy")

import numpy as np

lista = np.array([], dtype=int)

while len(lista) < 50:
  array = np.random.randint(10, 101)
  lista = np.append(lista,[array])

print(lista)

Exercicio 1 Numpy
[ 32  21  39  33  35  22  50  73  81  14  86  76  92  26  50  12  95  14
  86  80  95  13  51  68  96  21  47  79  61  86 100  87 100  29  58  53
  23  73  11  41  93  71  54  25  45  63  64  10  74  88]


In [65]:
print("Exercicio 2 Numpy")

matriz = np.array([[] , []], dtype = int)

for i in range(1):
 aleatorio1 = np.random.randint(1, 17)
 aleatorio2 = np.random.randint(1, 17)
 aleatorio3 = np.random.randint(1, 17)
 aleatorio4 = np.random.randint(1, 17)
 matriz = np.append(matriz, [[aleatorio1], [aleatorio3]], axis=1)
 matriz = np.append(matriz, [[aleatorio2], [aleatorio4]], axis=1)

 for i in range(1):
  aleatorio1 = np.random.randint(1, 17)
  aleatorio2 = np.random.randint(1, 17)
  aleatorio3 = np.random.randint(1, 17)
  aleatorio4 = np.random.randint(1, 17)
  matriz = np.append(matriz, [[aleatorio1], [aleatorio3]], axis=1)
  matriz = np.append(matriz, [[aleatorio2], [aleatorio4]], axis=1)

print(matriz)

Exercicio 2 Numpy
[[ 8  3 15 12]
 [11  4 14  2]]


In [66]:
print("Exercicio 3 Numpy")
import numpy as np
array_zeros = np.zeros((15,1), dtype=int)

#print(len(array_zeros))

for i in range(len(array_zeros)):
  if i >=5 and i <= 10:
    array_zeros[i]=1

print(array_zeros)

Exercicio 3 Numpy
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


In [67]:
print("Exercicio 4 Numpy")

import numpy as np
from scipy import stats

array = np.array([],dtype=int)

for i in range(100):
  aleatorio = np.random.randint(0, 1000)
  array = np.append(array,[aleatorio])


print(stats.mode(array).mode)

print(np.median(array))
print(array)


Exercicio 4 Numpy
525
528.5
[963 859 317 994 751 650 734 387 451  50 451 939 814 634 233 891  49 893
 525 226 571 890 328 281 146 260 590 525 222 604 195 596 525 304 673 955
 326 354 839 493  25 182 695 571 695 218  35 391 531  37 643 797 302 512
 669 356 641 306 163 364  55 128 885 526 813 156 846 409 657 793 350 659
 272 648 320  99 788 135 641 752 395 373 579 574 956 753 485 200 646 968
  86  20 816 917 823 455 708 954 750 884]


In [68]:
import numpy as np

print("Exercicio numpy 5")

array = np.random.randint(1, 101, 20)

print("Array original:", array)

array[array % 3 == 0] = -3

print("Array modificado:", array)

Exercicio numpy 5
Array original: [61 85 93 93 90 16 43 11 95 49 98 97 47 34 40 56 53 96  1 37]
Array modificado: [61 85 -3 -3 -3 16 43 11 95 49 98 97 47 34 40 56 53 -3  1 37]


In [69]:
import numpy as np

print("Exercicio numpy 6")

matriz = np.random.rand(5, 5)

print(matriz)

soma_colunas = np.sum(matriz, axis=0)

print("Soma de cada coluna:", soma_colunas)

Exercicio numpy 6
[[0.83235872 0.35438002 0.9025283  0.26168195 0.51658678]
 [0.67181085 0.83490335 0.95010772 0.66177839 0.54033914]
 [0.57483875 0.74650855 0.28633643 0.46918851 0.6483992 ]
 [0.12898234 0.63292793 0.85476924 0.93610117 0.31546724]
 [0.88224993 0.52299721 0.11673421 0.94056394 0.86618876]]
Soma de cada coluna: [3.09024059 3.09171705 3.1104759  3.26931395 2.88698112]


In [70]:
import numpy as np

print("Exercicio numpy 7")

array1 = np.random.randint(1, 101, 10)
array2 = np.random.randint(1, 101, 10)

print("Array 1:", array1)
print("Array 2:", array2)

correlacao = np.corrcoef(array1, array2)[0, 1]

print("Correlação:", correlacao)

Exercicio numpy 7
Array 1: [59 77 13 55 85 85 76 33 16 53]
Array 2: [82  5 18 25 12 89 68 24 10 67]
Correlação: 0.38134682289145566


In [71]:
import numpy as np

print("Exercicio numpy 8")

matriz = np.random.randint(1, 11, (3, 3))

print("Matriz original:")
print(matriz)

matriz_quadrado = matriz ** 2

print("Matriz ao quadrado:")
print(matriz_quadrado)

Exercicio numpy 8
Matriz original:
[[ 7  4  6]
 [10  5  8]
 [ 2  7  4]]
Matriz ao quadrado:
[[ 49  16  36]
 [100  25  64]
 [  4  49  16]]


In [72]:
import numpy as np

print("Exercicio numpy 9")

array = np.random.randint(1, 101, 10)

print("Array original:", array)

normalizado = (array - np.min(array)) / (np.max(array) - np.min(array))

print("Array normalizado:", normalizado)

Exercicio numpy 9
Array original: [59 74 95 85 53  4 46 12 37 38]
Array normalizado: [0.6043956  0.76923077 1.         0.89010989 0.53846154 0.
 0.46153846 0.08791209 0.36263736 0.37362637]


In [73]:
import numpy as np

print("Exercicio numpy 10")

matriz = np.eye(6, dtype=int)

np.fill_diagonal(matriz, np.arange(1, 7))

print(matriz)

Exercicio numpy 10
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [74]:
import numpy as np

print("Exercicio numpy 11")

array = np.random.randint(1, 101, 100)

valores, quantidade = np.unique(array, return_counts=True)

moda = valores[np.argmax(quantidade)]

print("Array:", array)
print("Moda:", moda)

Exercicio numpy 11
Array: [75 62 46 30 89  1 56 68 90 52 97  5 82 19 65  3 99 67 46 29 74 57 94 17
 75 91 22 54 67 55 92 52  3 19 28 10  9 64  4 16 82 99 52 59 18 21 80 43
 59 17  5  1 35 14 91 61 42 23 88 34 73 15 92 84 41 97 35 25 98 34 28 34
 34 74 99  3 37 18 10 97 97 36 33 99 17 32  3  8 29 20 22 12 60 38 77 45
 66 73 63 81]
Moda: 3


In [75]:
print("Exercicio 11 Numpy ")
import numpy as np
lista = np.array([], dtype=int)

while len(lista) < 10:

  array = np.random.randint(0, 101)
  if(array % 2==0):
   lista = np.append(lista,[array])

print(lista)

#print(sum(lista))


Exercicio 11 Numpy 
[92 56 22  2  0 36 38 50 92  2]


In [76]:
import numpy as np

print("Exercicio numpy 12")

matriz = np.random.randint(1, 101, (4, 4))

print("Matriz original:")
print(matriz)

np.fill_diagonal(matriz, 7)

print("Matriz modificada:")
print(matriz)

Exercicio numpy 12
Matriz original:
[[57 83 51 58]
 [11  4 85 18]
 [96 33 28 15]
 [79 33 91 35]]
Matriz modificada:
[[ 7 83 51 58]
 [11  7 85 18]
 [96 33  7 15]
 [79 33 91  7]]


In [77]:
import numpy as np

print("Exercicio numpy 13")

array = np.arange(2, 21, 2)

print("Array:", array)

soma_cumulativa = np.cumsum(array)

print("Soma cumulativa:", soma_cumulativa)

Exercicio numpy 13
Array: [ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: [  2   6  12  20  30  42  56  72  90 110]


In [78]:
import numpy as np

print("Exercicio numpy 14")

array1 = np.random.randint(1, 101, 10)
array2 = np.random.randint(1, 101, 10)

diferenca = array1 - array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Diferenças:", diferenca)

media = np.mean(diferenca)

print("Média das diferenças:", media)

Exercicio numpy 14
Array 1: [ 2 83 54 77 48 88 83 63 79 81]
Array 2: [77 59 45 70 38 41 22 63 27 20]
Diferenças: [-75  24   9   7  10  47  61   0  52  61]
Média das diferenças: 19.6


In [79]:
import numpy as np

print("Exercicio numpy 15")

array = np.random.randint(1, 101, 20)

print("Array original:", array)

array[array > 50] = 50

print("Array modificado:", array)

Exercicio numpy 15
Array original: [39 37 43 86 99 20 19 34 14 99  4 35 78 22 46 35 72 74 88 46]
Array modificado: [39 37 43 50 50 20 19 34 14 50  4 35 50 22 46 35 50 50 50 46]


In [80]:
import numpy as np

print("Exercicio numpy 16")

array = np.arange(1, 13)

print("Array:")
print(array)

matriz = array.reshape(3, 4)

print("Matriz 3x4:")
print(matriz)

Exercicio numpy 16
Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
import numpy as np

print("Exercicio numpy 17")

matriz = np.random.randint(1, 11, (4, 4))

print("Matriz original:")
print(matriz)

posicoes = np.arange(1, 17).reshape(4, 4)

resultado = matriz * posicoes

print("Posições:")
print(posicoes)

print("Resultado:")
print(resultado)

Exercicio numpy 17
Matriz original:
[[ 2  4  4  7]
 [ 7  4  1  5]
 [ 8  2  4  1]
 [ 9  6  4 10]]
Posições:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Resultado:
[[  2   8  12  28]
 [ 35  24   7  40]
 [ 72  20  44  12]
 [117  84  60 160]]


In [82]:
import numpy as np

print("Exercicio numpy 18")

array = np.random.randint(1, 101, 10)

print("Array original:", array)

array[array % 5 == 0] = 0

print("Array modificado:", array)

Exercicio numpy 18
Array original: [63 96 57 32 99 39 38  7 66  2]
Array modificado: [63 96 57 32 99 39 38  7 66  2]


In [83]:
import numpy as np

print("Exercicio numpy 19")

array1 = np.random.randint(1, 101, 20)
array2 = np.random.randint(1, 101, 20)

print("Array 1:", array1)
print("Array 2:", array2)

produto_escalar = np.dot(array1, array2)

modulo1 = np.linalg.norm(array1)
modulo2 = np.linalg.norm(array2)

cos_angulo = produto_escalar / (modulo1 * modulo2)

angulo = np.arccos(cos_angulo)

angulo_graus = np.degrees(angulo)

print("Ângulo em radianos:", angulo)
print("Ângulo em graus:", angulo_graus)

Exercicio numpy 19
Array 1: [ 60  64  76  56  50  59 100  61  52  54  88  74  19  17  44  63  49  66
  94  11]
Array 2: [76 46 46 28 15  8 86 70 34  7 66 27 95 17 24 96 30 64 32 87]
Ângulo em radianos: 0.6463278596147515
Ângulo em graus: 37.03185853764923


In [84]:
import numpy as np

print("Exercicio numpy 20")

matriz = np.random.randint(1, 101, (4, 4))

print("Matriz:")
print(matriz)

minimos = np.min(matriz, axis=1)

print("Valor mínimo de cada linha:", minimos)

Exercicio numpy 20
Matriz:
[[98 75 84 80]
 [66 58 84 86]
 [12 24 87 81]
 [12 23 14 82]]
Valor mínimo de cada linha: [75 58 12 12]


In [85]:
print("Exercícios de SciPy")

print("Exercicio 1 scipy")

import numpy as np
from scipy.integrate import quad

def f(x):
    return x**2 * np.sin(x)

resultado, erro = quad(f, 0, np.pi)

print("Resultado da integral:", resultado)

Exercícios de SciPy
Exercicio 1 scipy
Resultado da integral: 5.869604401089359


In [86]:
print("Exercicio 2 scipy")

import numpy as np
from scipy.integrate import solve_ivp

def f(x, y):
    return x - y

solucao = solve_ivp(
    f,
    [0, 10],
    [1],
    t_eval=np.linspace(0, 10, 100)
)

print("Valores de x:")
print(solucao.t)

print("Valores de y:")
print(solucao.y[0])

Exercicio 2 scipy
Valores de x:
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.979

In [87]:
print("Exercicio 3 scipy")

from scipy.optimize import root

def f(x):
    return x**4 - 3*x**3 + 2

chutes = [-2, 0, 1, 2, 3, 4]

raizes = []

for chute in chutes:
    resultado = root(f, chute)

    if resultado.success:
        raiz = resultado.x[0]

        if not any(abs(raiz - r) < 0.0001 for r in raizes):
            raizes.append(raiz)

print("Raízes:", raizes)

Exercicio 3 scipy
Raízes: [np.float64(0.9999999999999926), np.float64(2.919639565839426)]


In [88]:
print("Exercicio 4 scipy")

from scipy.optimize import minimize

def f(x):
    return -( -x**2 + 4*x + 1 )

resultado = minimize(f, [0])

print("Valor de x:", resultado.x[0])
print("Valor máximo:", -resultado.fun)

Exercicio 4 scipy
Valor de x: 2.000000026187685
Valor máximo: 4.999999999999999


In [89]:
print("Exercicio 5 scipy")

import numpy as np
from scipy.fft import fft, fftfreq

t = np.linspace(0, 1, 1000)

sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)

transformada = fft(sinal)

frequencias = fftfreq(len(t), t[1] - t[0])

print("Transformada de Fourier:")
print(transformada)

print("Frequências:")
print(frequencias)

Exercicio 5 scipy
Transformada de Fourier:
[ 1.00000000e+00-0.00000000e+00j  2.90244207e+00-4.99742397e+02j
  5.00232763e+02+3.81089174e+00j -8.06380114e-01+3.67890203e-01j
 -3.37543791e-01+2.62754553e-01j -1.94175185e-01+2.05542557e-01j
 -1.28486830e-01+1.69227876e-01j -9.22644511e-02+1.44002672e-01j
 -6.99757348e-02+1.25409353e-01j -5.52138945e-02+1.11113550e-01j
 -4.49026961e-02+9.97683610e-02j -3.74025732e-02+9.05396944e-02j
 -3.17699355e-02+8.28823599e-02j -2.74286372e-02+7.64244506e-02j
 -2.40099031e-02+7.09033135e-02j -2.12684088e-02+6.61280422e-02j
 -1.90356151e-02+6.19564711e-02j -1.71925288e-02+5.82805107e-02j
 -1.56531404e-02+5.50164896e-02j -1.43539982e-02+5.20986124e-02j
 -1.32474437e-02+4.94744174e-02j -1.22971070e-02+4.71015557e-02j
 -1.14748363e-02+4.49454620e-02j -1.07585610e-02+4.29776420e-02j
 -1.01307780e-02+4.11743937e-02j -9.57746030e-03+3.95158389e-02j
 -9.08725882e-03+3.79851813e-02j -8.65091067e-03+3.65681305e-02j
 -8.26079454e-03+3.52524512e-02j -7.91059311e-0

In [90]:
print("Exercicio 6 scipy")

import numpy as np
from scipy.linalg import inv

matriz = np.random.rand(5, 5)

inversa = inv(matriz)

print("Matriz:")
print(matriz)

print("Matriz inversa:")
print(inversa)

Exercicio 6 scipy
Matriz:
[[0.76375359 0.45964829 0.5763022  0.43404363 0.08435726]
 [0.61068327 0.00939218 0.54998405 0.17056076 0.12719127]
 [0.08824738 0.1172437  0.4985685  0.61214851 0.75329566]
 [0.95135212 0.02469058 0.55047856 0.00274336 0.29455031]
 [0.11570933 0.16021352 0.49999784 0.3594716  0.51008893]]
Matriz inversa:
[[ 0.51093686 -0.60132844  1.31553368  1.21885738 -2.58115413]
 [ 1.61144922 -3.49343697 -2.0613062   0.74880811  3.21631876]
 [-0.72516298  2.57157511 -2.54078583 -1.31843302  3.99224244]
 [ 0.74612388  1.8462233   3.116584   -1.5513669  -4.29046375]
 [-0.43703466 -2.58812065  0.64320862  1.87395491  0.64606993]]


In [91]:
print("Exercicio 7 scipy")

import numpy as np
from scipy.interpolate import CubicSpline

x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 3, 5, 4])

spline = CubicSpline(x, y)

novos_x = np.linspace(0, 4, 10)
novos_y = spline(novos_x)

print("Valores interpolados:")
print(novos_y)

Exercicio 7 scipy
Valores interpolados:
[0.         1.23639689 1.89117513 2.27160494 2.68495656 3.42203932
 4.39506173 5.13763146 5.16689529 4.        ]


In [92]:
print("Exercicio 8 scipy")

import numpy as np
from scipy.linalg import solve

A = np.array([
    [3, 2],
    [1, 4]
])

B = np.array([5, 6])

resultado = solve(A, B)

print("x =", resultado[0])
print("y =", resultado[1])

Exercicio 8 scipy
x = 0.7999999999999999
y = 1.3


In [93]:
print("Exercicio 9 scipy")

import numpy as np
from scipy.optimize import curve_fit

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 7, 8])

def funcao(x, a, b, c):
    return a*x**2 + b*x + c

parametros, _ = curve_fit(funcao, x, y)

print("Coeficientes:")
print("a =", parametros[0])
print("b =", parametros[1])
print("c =", parametros[2])

Exercicio 9 scipy
Coeficientes:
a = -0.07142857142857162
b = 1.9285714285714297
c = 0.19999999999999807


In [94]:
print("Exercicio 10 scipy")

from scipy.integrate import dblquad

def f(y, x):
    return x*y + x**2

resultado, erro = dblquad(
    f,
    0, 2,
    lambda x: 0,
    lambda x: 1
)

print("Resultado da integral dupla:", resultado)

Exercicio 10 scipy
Resultado da integral dupla: 3.666666666666667


In [95]:
print("Exercicio 11 scipy")

import numpy as np
from scipy.linalg import eig

matriz = np.random.randint(1, 10, (4, 4))

autovalores, autovetores = eig(matriz)

print("Matriz:")
print(matriz)

print("Autovalores:")
print(autovalores)

print("Autovetores:")
print(autovetores)

Exercicio 11 scipy
Matriz:
[[4 2 3 8]
 [2 7 1 9]
 [6 4 2 3]
 [8 1 9 3]]
Autovalores:
[18.07295429+0.j          3.4944372 +0.j         -2.78369575+3.48860232j
 -2.78369575-3.48860232j]
Autovetores:
[[-0.47376341+0.j         -0.37706251+0.j          0.36342015-0.33153016j
   0.36342015+0.33153016j]
 [-0.55986658+0.j          0.85549375+0.j          0.10424556-0.38887953j
   0.10424556+0.38887953j]
 [-0.41646616+0.j          0.22503515+0.j         -0.55444236+0.j
  -0.55444236-0.j        ]
 [-0.5372649 +0.j         -0.27443302+0.j          0.01826014+0.5368234j
   0.01826014-0.5368234j ]]


In [96]:
print("Exercicio 12 scipy")

import numpy as np
from scipy.optimize import brentq

def f(x):
    return np.exp(x) - x**2

raiz = brentq(f, -1, 0)

print("Raiz:", raiz)

Exercicio 12 scipy
Raiz: -0.7034674224983917


In [97]:
print("Exercicio 13 scipy")

import numpy as np
from scipy.linalg import det

matriz = np.random.randint(-10, 11, (6, 6))

resultado = det(matriz)

print("Matriz:")
print(matriz)

print("Determinante:", resultado)

Exercicio 13 scipy
Matriz:
[[  5  -1  10   0   2  10]
 [  7 -10   8   2  -2   2]
 [-10   3  -6  -3   4   6]
 [  4  -8   1   0  -5  10]
 [ -3  10   9  -9  -7  -4]
 [  9   6   4   7   3   7]]
Determinante: -529882.0000000002


In [98]:
print("Exercicio 14 scipy")

from scipy.optimize import minimize

def f(valores):
    x, y = valores
    return (x - 2)**2 + (y - 3)**2

resultado = minimize(f, [0, 0])

print("x =", resultado.x[0])
print("y =", resultado.x[1])

print("Valor mínimo:", resultado.fun)

Exercicio 14 scipy
x = 1.9999999892076392
y = 2.9999999917462903
Valor mínimo: 1.84598775337616e-16


In [99]:
print("Exercicio 15 scipy")

import numpy as np
from scipy.fft import ifft

sinal = np.random.rand(10) + 1j * np.random.rand(10)

resultado = ifft(sinal)

print("Sinal complexo:")
print(sinal)

print("Transformada inversa:")
print(resultado)

Exercicio 15 scipy
Sinal complexo:
[0.95291296+0.53118135j 0.09089183+0.63418892j 0.29433381+0.82036536j
 0.64227264+0.65596439j 0.99085757+0.28611746j 0.17292405+0.02608865j
 0.09891759+0.00562421j 0.28339479+0.94579599j 0.91561417+0.47206159j
 0.22237455+0.20633682j]
Transformada inversa:
[ 0.4664494 +0.45837248j -0.02323377+0.1050905j  -0.06835816-0.29837422j
  0.01506481+0.14632393j  0.11709815+0.08662326j  0.18407783-0.03530248j
  0.01304066+0.02049664j  0.14292629-0.02917091j  0.03468847+0.01151685j
  0.07115929+0.06560531j]


In [100]:
print("Exercicio 16 scipy")

import numpy as np
from scipy.integrate import solve_ivp

def f(x, valores):
    y = valores[0]
    derivada = valores[1]

    return [derivada, -y]

solucao = solve_ivp(
    f,
    [0, 10],
    [1, 0],
    t_eval=np.linspace(0, 10, 100)
)

print("Valores de y:")
print(solucao.y[0])

Exercicio 16 scipy
Valores de y:
[ 1.          0.99490282  0.97966871  0.95445419  0.91950576  0.87517179
  0.82190263  0.76025061  0.69086392  0.61444408  0.53177528  0.4436931
  0.35107753  0.25485297  0.15598823  0.0554965  -0.04556458 -0.14610107
 -0.24517868 -0.34178443 -0.43488533 -0.52351462 -0.60677172 -0.68382229
 -0.75389819 -0.81629749 -0.8703845  -0.91560733 -0.95158056 -0.97788772
 -0.99420508 -1.00033127 -0.99618736 -0.98181677 -0.95738534 -0.92318132
 -0.87961533 -0.82717378 -0.76632692 -0.69768137 -0.62191812 -0.53978807
 -0.45211204 -0.35978074 -0.26375482 -0.16506482 -0.06474696  0.03627043
  0.13691409  0.23613526  0.3329234   0.42630621  0.5153496   0.59915775
  0.67687302  0.74767604  0.81085893  0.86584822  0.91201712  0.94885093
  0.97595255  0.99304249  0.99995885  0.99665738  0.98321139  0.95980956
  0.92669317  0.88416402  0.83262207  0.77256087  0.70456754  0.62932278
  0.54760086  0.46026966  0.36829058  0.27264826  0.17420813  0.07400149
 -0.02693842 -0.127

In [101]:
print("Exercicio 17 scipy")

from scipy.special import cbrt

resultado = cbrt(27)

print("Raiz cúbica de 27:", resultado)

Exercicio 17 scipy
Raiz cúbica de 27: 3.0


In [102]:
print("Exercicio 18 scipy")

import numpy as np
from scipy.interpolate import CubicSpline

x = np.array([1, 2, 3, 4, 5])
y = x**2

spline = CubicSpline(x, y)

novos_x = np.array([1.5, 2.5, 3.5, 4.5])

resultado = spline(novos_x)

print("Valores interpolados:")
print(resultado)

Exercicio 18 scipy
Valores interpolados:
[ 2.25  6.25 12.25 20.25]


In [103]:
print("Exercicio 19 scipy")

import numpy as np
from scipy.fft import fft

x = np.linspace(0, 1, 100)

sinal = (
    np.sin(2 * np.pi * 5 * x)
    + np.cos(2 * np.pi * 10 * x)
)

resultado = fft(sinal)

print("Transformada de Fourier:")
print(resultado)

Exercicio 19 scipy
Transformada de Fourier:
[ 1.        -0.00000000e+00j  1.01566014-1.72563321e-01j
  1.06735447-3.99779412e-01j  1.1760994 -8.04387183e-01j
  1.43841818-1.94765560e+00j  9.05218415-4.87198320e+01j
  0.96925143+3.11786543e+00j  1.53470056+1.88463489e+00j
  2.31010837+1.67924879e+00j  4.36794784+2.12631048e+00j
 46.79892028+1.59246634e+01j -5.1591407 -1.23176291e+00j
 -2.39750249-3.90480406e-01j -1.54396422-1.59595432e-01j
 -1.130775  -6.24616971e-02j -0.88834671-1.37857271e-02j
 -0.72980085+1.28964681e-02j -0.61859566+2.82041027e-02j
 -0.53668233+3.71061234e-02j -0.47412292+4.21801827e-02j
 -0.42499726+4.48663880e-02j -0.38556142+4.60154873e-02j
 -0.35333381+4.61522982e-02j -0.32660606+4.56118643e-02j
 -0.3041648 +4.46140319e-02j -0.28512539+4.33062776e-02j
 -0.26882839+4.17892915e-02j -0.25477273+4.01327748e-02j
 -0.24257136+3.83854753e-02j -0.23192093+3.65817219e-02j
 -0.22258067+3.47457693e-02j -0.2143573 +3.28947421e-02j
 -0.20709415+3.10406619e-02j -0.20066309+2.9

In [104]:
print("Exercicio 20 scipy")

import numpy as np
from scipy.linalg import solve

A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 2, 4]
])

B = np.array([4, 5, 6])

resultado = solve(A, B)

print("x =", resultado[0])
print("y =", resultado[1])
print("z =", resultado[2])

Exercicio 20 scipy
x = 1.2307692307692308
y = 0.6923076923076923
z = 0.8461538461538461


In [106]:
print("Exercicio Pandas")

print("Exercicio 1 pandas")

import pandas as pd

dados = {
    "Produto": ["Arroz", "Feijão", "Macarrão", "Leite", "Café"],
    "Preço": [25.00, 8.50, 6.00, 5.50, 15.00],
    "Quantidade": [10, 20, 15, 30, 8]
}

df = pd.DataFrame(dados)

print(df)



Exercicio Pandas
Exercicio 1 pandas
    Produto  Preço  Quantidade
0     Arroz   25.0          10
1    Feijão    8.5          20
2  Macarrão    6.0          15
3     Leite    5.5          30
4      Café   15.0           8


In [112]:
print("Exercicio 2 - Pandas")

from google.colab import files
import pandas as pd

files.upload()

df = pd.read_excel("vendas.xlsx")

print(df.head(10))

Exercicio 2 - Pandas


Saving vendas.xlsx to vendas.xlsx
  Produto,Quantidade,Valor Unitário (R$)
0                     Arroz 5kg,10,25.90
1                     Feijão 1kg,15,8.50
2                  Macarrão 500g,20,4.80
3             Óleo de soja 900ml,12,7.20
4                     Açúcar 2kg,18,6.40
5                        Sal 1kg,25,2.30
6                      Café 500g,8,14.90
7                       Leite 1L,30,5.60
8           Farinha de trigo 1kg,14,5.10
9           Molho de tomate 340g,22,3.70


In [124]:
print("Exercicio 3 - Pandas")

import pandas as pd

df = pd.read_excel("vendas.xlsx")

df = df.iloc[:, 0].str.split(",", expand=True)


df.columns = ["Produto", "Quantidade", "Valor Unitário (R$)"]

df["Valor Unitário (R$)"] = pd.to_numeric(df["Valor Unitário (R$)"])

resultado = df[df["Valor Unitário (R$)"] > 100]

print(resultado)

Exercicio 3 - Pandas
Empty DataFrame
Columns: [Produto, Quantidade, Valor Unitário (R$)]
Index: []


In [120]:
print("Exercicio 4 - Pandas")

import pandas as pd

df = pd.read_excel("vendas.xlsx")

df = df.iloc[:, 0].str.split(",", expand=True)


df.columns = ["Produto", "Quantidade", "Valor Unitário (R$)"]


df["Quantidade"] = pd.to_numeric(df["Quantidade"])
df["Valor Unitário (R$)"] = pd.to_numeric(df["Valor Unitário (R$)"])


df["Desconto"] = df["Valor Unitário (R$)"] * 0.10

print(df)

Exercicio 4 - Pandas
                       Produto  Quantidade  Valor Unitário (R$)  Desconto
0                    Arroz 5kg          10                 25.9      2.59
1                   Feijão 1kg          15                  8.5      0.85
2                Macarrão 500g          20                  4.8      0.48
3           Óleo de soja 900ml          12                  7.2      0.72
4                   Açúcar 2kg          18                  6.4      0.64
5                      Sal 1kg          25                  2.3      0.23
6                    Café 500g           8                 14.9      1.49
7                     Leite 1L          30                  5.6      0.56
8         Farinha de trigo 1kg          14                  5.1      0.51
9         Molho de tomate 340g          22                  3.7      0.37
10           Biscoito recheado          16                  4.2      0.42
11             Sabão em pó 1kg          10                 12.5      1.25
12    Detergente 