<a href="https://colab.research.google.com/github/DevKaiqueTeixeira/IA/blob/main/ExercicioLista2_Python_KaiqueDeLimaTeixeira_6periodo_TurmaC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Lista 2")

print("Estudos fora da lista")

import numpy as np

array = np.array([1,2,3,4,5,6])
print(array)

array_zeros = np.zeros((3,3))

array_rand = np.random.rand(4)

print(array_zeros)
print(array_rand)

#Soma com NUMPY
array1 = np.array([5,5,5,5,5])

array2 = np.array([1,2,3,4,5,])

soma = np.add(array1,array2)

produto=np.dot(array1,array2)

print(f"Soma: {soma}")

media = np.mean(array1)
print(f"Média: {media}")
print(f"Produto: {produto}")
desvio = np.std(array1)

print(f"Desvio padrão: {desvio}")

#Fatiamento de array


arrayfatia = np.array([[1,2,3] , [4,5,6,], [7,8,9]])
primeira_linha = arrayfatia[0, :]
array_reshaped = np.reshape(arrayfatia, (1, 9 ))
print(arrayfatia)
print(array_reshaped)

a = np.array([[1,2] , [4,5]])

inversionMatriz = np.linalg.det(a)
print(f"Inversão matriz: {inversionMatriz}")

aleatorios= np.random.randint(10)
print(f"Aleatório {aleatorios}")

Lista 2
Estudos fora da lista
[1 2 3 4 5 6]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0.36618585 0.40749022 0.50373621 0.94785785]
Soma: [ 6  7  8  9 10]
Média: 5.0
Produto: 75
Desvio padrão: 0.0
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
Inversão matriz: -2.9999999999999996
Aleatório 9


In [ ]:
print("Exercício  Manipulação array")
import numpy as np

#array 3x3
array = np.random.randint(0, 10, (3, 3))
print(f"Array padrão: ")
print(array)

max_value =  np.max(array)
print(f"Maior número: {max_value}")

min_value =  np.min(array)
print(f"Maior número: {min_value}")

sum_value = np.sum(array)
print(f"Soma dos elementos: {sum_value}")



Exercício 1 Manipulação array
Array padrão: 
[[4 9 9]
 [4 7 3]
 [2 9 0]]
Maior número: 9
Maior número: 0
Soma dos elementos: 47


In [ ]:
print("Exercício  Produto escalar entre vetores")

import numpy as np

vetor1 = np.array([1,2,3])
vetor2 = np.array([4,5,6])

produto_escalar = np.dot(vetor1, vetor2)
print(f"Produto escalar: {produto_escalar}")

Exercício 2 Produto escalar entre vetores
Produto escalar: 32


In [ ]:
print("Exercício  Operações matemática ")

import numpy as np

array = np.array([[1,2], [3,4]])

array2 = np.array([[1,2], [3,4]])

soma = array + array2

print(f"Soma dos arrays: {soma}")

multiplicar = array * array2
print(f"Multiplicar dos arrays: {multiplicar}")

subtrair = array - array2
print(f"Subtrair dos arrays: {subtrair}")





Exercício 3 Operações matemática 
Contas
Soma dos arrays: [[2 4]
 [6 8]]
Multiplicar dos arrays: [[ 1  4]
 [ 9 16]]
Subtrair dos arrays: [[0 0]
 [0 0]]


In [ ]:
print("Exercício 4 Otimização de Funções")

from scipy.optimize import minimize

def f(x):
  return 10+10+10


resultado = minimize(f,0)

print(f"Minimo encontrado{resultado.fun}")
print(f"Valor de X {resultado.x}")

Exercício 4 Otimização de Funções
Minimo encontrado30
Minimo encontrado[0.]


In [22]:
print("Exercicio 1 Numpy")

import numpy as np

lista = np.array([], dtype=int)

while len(lista) < 50:
  array = np.random.randint(10, 101)
  lista = np.append(lista,[array])

print(lista)

Exercicio 1 Numpy
[96 56 36 29 70 80 92 44 93 83 76 70 21 97 19 56 28 81 48 47 62 93 57 12
 41 65 75 83 97 34 21 71 86 79 71 32 49 93 31 88 37 70 51 98 60 44 96 47
 15 50]


In [47]:
print("Exercicio 2 Numpy")

matriz = np.array([[] , []], dtype = int)

for i in range(1):
 aleatorio1 = np.random.randint(1, 17)
 aleatorio2 = np.random.randint(1, 17)
 aleatorio3 = np.random.randint(1, 17)
 aleatorio4 = np.random.randint(1, 17)
 matriz = np.append(matriz, [[aleatorio1], [aleatorio3]], axis=1)
 matriz = np.append(matriz, [[aleatorio2], [aleatorio4]], axis=1)

 for i in range(1):
  aleatorio1 = np.random.randint(1, 17)
  aleatorio2 = np.random.randint(1, 17)
  aleatorio3 = np.random.randint(1, 17)
  aleatorio4 = np.random.randint(1, 17)
  matriz = np.append(matriz, [[aleatorio1], [aleatorio3]], axis=1)
  matriz = np.append(matriz, [[aleatorio2], [aleatorio4]], axis=1)

print(matriz)

Exercicio 2 Numpy
[[ 9 15 12  5]
 [ 9 10 11 14]]


In [1]:
print("Exercicio 3 Numpy")

array_zeros = np.zeros((15,1))

#print(len(array_zeros))

for i in range(len(array_zeros)):
  if i >=5 and i <= 10:
    array_zeros[i]=1

print(array_zeros)

Exercicio 3 Numpy


NameError: name 'np' is not defined

In [1]:
print("Exercicio 11 Numpy ")
import numpy as np
lista = np.array([], dtype=int)

while len(lista) < 10:

  array = np.random.randint(0, 101)
  if(array % 2==0):
   lista = np.append(lista,[array])

print(lista)

#print(sum(lista))


Exercicio 11 
[22 54 96 12 64 40 72  6 72 30]
